version: '3'
services:
  api:
    build: .
    volumes:
      - ./:/go/src/github.com/tommy-sho/redis-pubsub
    ports:
      - '8080:8080'
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - '6379:6379'